all:
  ubuntu:

ubuntu:
  hosts:
    hx-jumper:
      ansible_host: 10.51.71.50
      ansible_port: 22
      ansible_connection: local
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_user: "{{ lookup('env','ANSIBLE_SUDO_USER') }}"
      ansible_sudo_pass: "{{ lookup('env','ANSIBLE_SUDO_PASSWORD') }}"
    hx-vm-appd01:
      ansible_host: 10.51.71.51
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_user: "{{ lookup('env','ANSIBLE_SUDO_USER') }}"
      ansible_sudo_pass: "{{ lookup('env','ANSIBLE_SUDO_PASSWORD') }}"


